version: '3'

services:
  # Database
  # database:
  #   image: database
  #   build: ./backend/database
  #   volumes:
  #     - ./backend/database/data:/data/db
  #   networks:
  #     - back

  # API
  api:
    image: api
    build: ./backend/api
    command: npx nodemon backend/api/index.js
    volumes:
      - ./backend/api:/src
      - nodemodules:/src/node_modules
    ports:
      - 8080:8080
    networks:
      - front
      - back

  # Web - Single Page Application
  # web:
  #   image: web
  #   build: ./frontend/app/web
  #   depends_on:
  #     - api
  #   networks:
  #     - front

networks:
  front:
    driver: bridge
  back:
    driver: bridge

volumes:
  nodemodules: {}