version: "3"

services:
  # API
  api:
    image: api
    build: ./backend/api
    command: npx nodemon backend/api/index.js
    volumes:
      - ./backend/api:/src
      - nodemodules-api:/src/node_modules
    ports:
      - 8080:8080

  # Web - Single Page Application
  web:
    image: web
    build: ./frontend/app/web
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app/web:/usr/src/app
      # - nodemodules-web:/usr/src/app/node_modules

volumes:
  nodemodules-api: {}
  nodemodules-web: {}
